### PR TITLE
feat: add Alan's haslam model

### PR DESCRIPTION
**Pull request by steven-murray**
This add's Alan's sky model, and tests that it is constructed with similar (but not identical) values to the existing LAMBDA-based Haslam map. Alan's map seems to include bright sources that the LAMBDA one does not.

It also adds two extra demos that show how to recover Alan's beam-factor (almost exactly).

### CODE REVIEW

**Comment by steven-murray** [comment]
@nmahesh1412 this is now ready to go I think. 

Your old beam-factor files will _not_ work anymore, but the new format is much nicer and easier, I think. There is an example notebook in the docs on how to create the beam factor files (similar to before). When applying the beam factor in the YAML file, and trying to be similar to Alan, you'll need something like:

```
- function: 'apply_beam_correction'
   params:
      beam: !hickle YOUR_BEAM_FILE.h5
      freq_model: !Model
        model: fourier
        n_terms: 31
        transform: !ShiftTransform
            shift: 75.0
        period=1.2*60.0,  # This is 1.2 * the bandwidth
      resample_beam_lsts: false
      integrate_before_ratio: true
```

**Review by nmahesh1412 — COMMENTED** [review]
After this fix, the approximate_temperature step doesnt seem to be working

**Comment by steven-murray** [comment]
@nmahesh1412 is it giving an error message?

**Review by nmahesh1412 — APPROVED** [review]
The Alan beam model factor method works fine.

**Pull request merged**
